#import "ZNMenuPrivate.h"
#import "ZNUIComponents.h"
#import <QuartzCore/QuartzCore.h>
@implementation ZNMenuViewController (Layout)
-(UIView*)sectionHeader:(NSString*)t symbol:(NSString*)sym{UIView*v=[UIView new];v.translatesAutoresizingMaskIntoConstraints=NO;UIImageView*i=[[UIImageView alloc]initWithImage:ZNSymbol(sym,16)];i.translatesAutoresizingMaskIntoConstraints=NO;i.tintColor=ZNColor(.13,.87,1,1);UILabel*l=ZNLabel(t,12.2,UIFontWeightBold,ZNColor(.65,.86,1,1));[v addSubview:i];[v addSubview:l];[NSLayoutConstraint activateConstraints:@[[v.heightAnchor constraintEqualToConstant:28],[i.leadingAnchor constraintEqualToAnchor:v.leadingAnchor],[i.centerYAnchor constraintEqualToAnchor:v.centerYAnchor],[i.widthAnchor constraintEqualToConstant:20],[i.heightAnchor constraintEqualToConstant:20],[l.leadingAnchor constraintEqualToAnchor:i.trailingAnchor constant:8],[l.centerYAnchor constraintEqualToAnchor:v.centerYAnchor]]];return v;}
-(UIButton*)tabButton:(NSString*)t symbol:(NSString*)sym tag:(NSInteger)tag selected:(BOOL)sel{UIButton*b=[UIButton buttonWithType:UIButtonTypeSystem];b.tag=tag;b.translatesAutoresizingMaskIntoConstraints=NO;b.layer.cornerRadius=11;b.layer.borderWidth=1;b.layer.borderColor=(sel?ZNColor(.05,.88,1,.92):ZNColor(.22,.48,.76,.55)).CGColor;b.backgroundColor=sel?ZNColor(.02,.20,.34,.90):ZNColor(.025,.08,.16,.82);b.layer.shadowColor=(sel?ZNColor(0,.83,1,1):ZNColor(.12,.35,.70,1)).CGColor;b.layer.shadowOpacity=sel?.75:.22;b.layer.shadowRadius=sel?10:5;b.layer.shadowOffset=CGSizeZero;[b setTitle:[NSString stringWithFormat:@"  [%@]",t] forState:UIControlStateNormal];[b setTitleColor:(sel?ZNColor(.20,.94,1,1):ZNColor(.65,.75,.90,1)) forState:UIControlStateNormal];b.titleLabel.font=[UIFont systemFontOfSize:10.5 weight:UIFontWeightSemibold];[b setImage:ZNSymbol(sym,15) forState:UIControlStateNormal];b.tintColor=sel?ZNColor(.18,.93,1,1):ZNColor(.42,.67,.92,1);[b addTarget:self action:@selector(tabTapped:) forControlEvents:UIControlEventTouchUpInside];return b;}
-(void)buildMenu{
self.panel=[UIView new];self.panel.layer.cornerRadius=22;self.panel.layer.borderWidth=1.2;self.panel.layer.borderColor=ZNColor(0,.88,1,.82).CGColor;self.panel.layer.shadowColor=ZNColor(.55,.05,1,1).CGColor;self.panel.layer.shadowOpacity=.48;self.panel.layer.shadowRadius=22;self.panel.layer.shadowOffset=CGSizeZero;[self.view addSubview:self.panel];
self.panelGradient=[CAGradientLayer layer];self.panelGradient.colors=@[(id)ZNColor(.01,.07,.14,.96).CGColor,(id)ZNColor(.03,.05,.13,.94).CGColor,(id)ZNColor(.16,.015,.20,.91).CGColor];self.panelGradient.startPoint=CGPointMake(0,0);self.panelGradient.endPoint=CGPointMake(1,1);self.panelGradient.cornerRadius=22;[self.panel.layer insertSublayer:self.panelGradient atIndex:0];
self.panelInner=[UIView new];self.panelInner.translatesAutoresizingMaskIntoConstraints=NO;self.panelInner.layer.cornerRadius=18;self.panelInner.layer.borderWidth=1;self.panelInner.layer.borderColor=ZNColor(.72,.10,1,.34).CGColor;self.panelInner.backgroundColor=ZNColor(.01,.035,.09,.24);[self.panel addSubview:self.panelInner];
UILabel*logo=ZNLabel(@"X",36,UIFontWeightBlack,ZNColor(.18,.96,1,1));logo.layer.shadowColor=ZNColor(0,.9,1,1).CGColor;logo.layer.shadowOpacity=.9;logo.layer.shadowRadius=8;UILabel*title=ZNLabel(@"XPLORE MOBILE MOD MENU",16.2,UIFontWeightBold,UIColor.whiteColor);UILabel*ver=ZNLabel(@"v4.2 (2026)",11.2,UIFontWeightMedium,ZNColor(.67,.81,.96,1));UILabel*tag=ZNLabel(@"P L A Y   B E Y O N D   L I M I T S",6.4,UIFontWeightSemibold,ZNColor(.30,.72,1,.90));UILabel*nav=ZNLabel(@"MODS  ·  VISUALS  ·  FREEDOM   ·   +",8.5,UIFontWeightSemibold,ZNColor(.54,.75,.98,.92));ZNNeonSwitch*master=[ZNNeonSwitch new];[master setOn:YES animated:NO];master.accessibilityIdentifier=@"master";[master addTarget:self action:@selector(switchChanged:) forControlEvents:UIControlEventValueChanged];for(UIView*v in @[logo,title,ver,tag,nav,master])[self.panelInner addSubview:v];
UIView*mf=[UIView new];mf.translatesAutoresizingMaskIntoConstraints=NO;mf.layer.cornerRadius=13;mf.layer.borderWidth=1;mf.layer.borderColor=ZNColor(0,.86,1,.65).CGColor;mf.backgroundColor=ZNColor(.01,.06,.12,.35);[self.panelInner insertSubview:mf belowSubview:master];UIView*div=[UIView new];div.translatesAutoresizingMaskIntoConstraints=NO;div.backgroundColor=ZNColor(.08,.63,.94,.34);[self.panelInner addSubview:div];
UIView*body=[UIView new];body.translatesAutoresizingMaskIntoConstraints=NO;[self.panelInner addSubview:body];ZNGlowPanel*lt=[ZNGlowPanel new];lt.translatesAutoresizingMaskIntoConstraints=NO;ZNGlowPanel*lb=[ZNGlowPanel new];lb.translatesAutoresizingMaskIntoConstraints=NO;ZNGlowPanel*r=[ZNGlowPanel new];r.translatesAutoresizingMaskIntoConstraints=NO;[body addSubview:lt];[body addSubview:lb];[body addSubview:r];
UIView*gh=[self sectionHeader:@"GLOBAL TWEAKS" symbol:@"gearshape.fill"];ZNControlRow*god=[[ZNControlRow alloc]initWithTitle:@"GOD MODE (Immunity)" symbol:@"shield.fill" on:YES];god.neonSwitch.accessibilityIdentifier=@"god_mode";[god.neonSwitch addTarget:self action:@selector(switchChanged:) forControlEvents:UIControlEventValueChanged];ZNControlRow*unlock=[[ZNControlRow alloc]initWithTitle:@"UNLOCK ALL CONTENT" symbol:@"lock.fill" on:NO];unlock.neonSwitch.accessibilityIdentifier=@"unlock_all";[unlock.neonSwitch addTarget:self action:@selector(switchChanged:) forControlEvents:UIControlEventValueChanged];for(UIView*v in @[gh,god,unlock])[lt addSubview:v];
UIView*ph=[self sectionHeader:@"PLAYER CONTROL" symbol:@"slider.horizontal.3"];self.speedRow=[[ZNSliderRow alloc]initWithTitle:@"WALK SPEED" symbol:@"figure.walk" value:.52 valueText:@"1.0x" tint:ZNColor(0,.86,1,1)];self.speedRow.slider.accessibilityIdentifier=@"walk_speed";[self.speedRow.slider addTarget:self action:@selector(sliderChanged:) forControlEvents:UIControlEventValueChanged];self.fovRow=[[ZNSliderRow alloc]initWithTitle:@"FOV (Field of view)" symbol:@"eye.fill" value:.58 valueText:@"75°" tint:ZNColor(.92,.04,1,1)];self.fovRow.slider.accessibilityIdentifier=@"fov";[self.fovRow.slider addTarget:self action:@selector(sliderChanged:) forControlEvents:UIControlEventValueChanged];for(UIView*v in @[ph,self.speedRow,self.fovRow])[lb addSubview:v];
UIImageView*cam=[[UIImageView alloc]initWithImage:ZNSymbol(@"camera.fill",18)];cam.translatesAutoresizingMaskIntoConstraints=NO;cam.tintColor=ZNColor(.15,.86,1,1);UILabel*gt=ZNLabel(@"PHOTO PRESETS & GALLERY",13,UIFontWeightBold,ZNColor(.67,.85,1,1));UIImageView*search=[[UIImageView alloc]initWithImage:ZNSymbol(@"magnifyingglass",18)];search.translatesAutoresizingMaskIntoConstraints=NO;search.tintColor=ZNColor(.45,.78,1,1);UIView*gd=[UIView new];gd.translatesAutoresizingMaskIntoConstraints=NO;gd.backgroundColor=ZNColor(.05,.68,1,.30);UILabel*pt=ZNLabel(@"PHOTO PRESETS",11.8,UIFontWeightSemibold,UIColor.whiteColor);UILabel*ps=ZNLabel(@"Implementable UICollectionView grid",9.4,UIFontWeightRegular,ZNColor(.72,.80,.92,1));for(UIView*v in @[cam,gt,search,gd,pt,ps])[r addSubview:v];
UICollectionViewFlowLayout*f=[UICollectionViewFlowLayout new];f.minimumInteritemSpacing=8;f.minimumLineSpacing=8;self.grid=[[UICollectionView alloc]initWithFrame:CGRectZero collectionViewLayout:f];self.grid.translatesAutoresizingMaskIntoConstraints=NO;self.grid.backgroundColor=UIColor.clearColor;self.grid.dataSource=self;self.grid.delegate=self;self.grid.showsVerticalScrollIndicator=YES;self.grid.indicatorStyle=UIScrollViewIndicatorStyleWhite;[self.grid registerClass:ZNPresetCell.class forCellWithReuseIdentifier:@"preset"];[r addSubview:self.grid];
UIStackView*tabs=[UIStackView new];tabs.translatesAutoresizingMaskIntoConstraints=NO;tabs.axis=UILayoutConstraintAxisHorizontal;tabs.spacing=10;tabs.distribution=UIStackViewDistributionFillEqually;[tabs addArrangedSubview:[self tabButton:@"TWEAKS" symbol:@"slider.horizontal.3" tag:0 selected:YES]];[tabs addArrangedSubview:[self tabButton:@"PRESETS" symbol:@"photo.fill" tag:1 selected:NO]];[tabs addArrangedSubview:[self tabButton:@"SETTINGS" symbol:@"gearshape.fill" tag:2 selected:NO]];[tabs addArrangedSubview:[self tabButton:@"LOGS" symbol:@"doc.text.fill" tag:3 selected:NO]];[self.panelInner addSubview:tabs];
[NSLayoutConstraint activateConstraints:@[
[self.panelInner.leadingAnchor constraintEqualToAnchor:self.panel.leadingAnchor constant:4],[self.panelInner.trailingAnchor constraintEqualToAnchor:self.panel.trailingAnchor constant:-4],[self.panelInner.topAnchor constraintEqualToAnchor:self.panel.topAnchor constant:4],[self.panelInner.bottomAnchor constraintEqualToAnchor:self.panel.bottomAnchor constant:-4],
[logo.leadingAnchor constraintEqualToAnchor:self.panelInner.leadingAnchor constant:24],[logo.topAnchor constraintEqualToAnchor:self.panelInner.topAnchor constant:12],[title.leadingAnchor constraintEqualToAnchor:logo.trailingAnchor constant:13],[title.topAnchor constraintEqualToAnchor:self.panelInner.topAnchor constant:13],[ver.leadingAnchor constraintEqualToAnchor:title.leadingAnchor],[ver.topAnchor constraintEqualToAnchor:title.bottomAnchor constant:1],[tag.leadingAnchor constraintEqualToAnchor:title.leadingAnchor],[tag.topAnchor constraintEqualToAnchor:ver.bottomAnchor constant:2],[nav.trailingAnchor constraintEqualToAnchor:mf.leadingAnchor constant:-16],[nav.centerYAnchor constraintEqualToAnchor:title.centerYAnchor],[mf.trailingAnchor constraintEqualToAnchor:self.panelInner.trailingAnchor constant:-18],[mf.topAnchor constraintEqualToAnchor:self.panelInner.topAnchor constant:12],[mf.widthAnchor constraintEqualToConstant:84],[mf.heightAnchor constraintEqualToConstant:43],[master.centerXAnchor constraintEqualToAnchor:mf.centerXAnchor],[master.centerYAnchor constraintEqualToAnchor:mf.centerYAnchor],[div.leadingAnchor constraintEqualToAnchor:self.panelInner.leadingAnchor constant:18],[div.trailingAnchor constraintEqualToAnchor:self.panelInner.trailingAnchor constant:-18],[div.topAnchor constraintEqualToAnchor:self.panelInner.topAnchor constant:66],[div.heightAnchor constraintEqualToConstant:1],
[body.leadingAnchor constraintEqualToAnchor:self.panelInner.leadingAnchor constant:14],[body.trailingAnchor constraintEqualToAnchor:self.panelInner.trailingAnchor constant:-14],[body.topAnchor constraintEqualToAnchor:div.bottomAnchor constant:10],[body.bottomAnchor constraintEqualToAnchor:tabs.topAnchor constant:-10],[lt.leadingAnchor constraintEqualToAnchor:body.leadingAnchor],[lt.topAnchor constraintEqualToAnchor:body.topAnchor],[lt.widthAnchor constraintEqualToAnchor:body.widthAnchor multiplier:.34],[lt.heightAnchor constraintEqualToAnchor:body.heightAnchor multiplier:.43],[lb.leadingAnchor constraintEqualToAnchor:lt.leadingAnchor],[lb.trailingAnchor constraintEqualToAnchor:lt.trailingAnchor],[lb.topAnchor constraintEqualToAnchor:lt.bottomAnchor constant:9],[lb.bottomAnchor constraintEqualToAnchor:body.bottomAnchor],[r.leadingAnchor constraintEqualToAnchor:lt.trailingAnchor constant:10],[r.trailingAnchor constraintEqualToAnchor:body.trailingAnchor],[r.topAnchor constraintEqualToAnchor:body.topAnchor],[r.bottomAnchor constraintEqualToAnchor:body.bottomAnchor],
[gh.leadingAnchor constraintEqualToAnchor:lt.leadingAnchor constant:14],[gh.trailingAnchor constraintEqualToAnchor:lt.trailingAnchor constant:-14],[gh.topAnchor constraintEqualToAnchor:lt.topAnchor constant:8],[god.leadingAnchor constraintEqualToAnchor:lt.leadingAnchor constant:10],[god.trailingAnchor constraintEqualToAnchor:lt.trailingAnchor constant:-10],[god.topAnchor constraintEqualToAnchor:gh.bottomAnchor constant:3],[unlock.leadingAnchor constraintEqualToAnchor:god.leadingAnchor],[unlock.trailingAnchor constraintEqualToAnchor:god.trailingAnchor],[unlock.topAnchor constraintEqualToAnchor:god.bottomAnchor constant:6],[unlock.bottomAnchor constraintLessThanOrEqualToAnchor:lt.bottomAnchor constant:-9],
[ph.leadingAnchor constraintEqualToAnchor:lb.leadingAnchor constant:14],[ph.trailingAnchor constraintEqualToAnchor:lb.trailingAnchor constant:-14],[ph.topAnchor constraintEqualToAnchor:lb.topAnchor constant:7],[self.speedRow.leadingAnchor constraintEqualToAnchor:lb.leadingAnchor constant:15],[self.speedRow.trailingAnchor constraintEqualToAnchor:lb.trailingAnchor constant:-15],[self.speedRow.topAnchor constraintEqualToAnchor:ph.bottomAnchor constant:3],[self.fovRow.leadingAnchor constraintEqualToAnchor:self.speedRow.leadingAnchor],[self.fovRow.trailingAnchor constraintEqualToAnchor:self.speedRow.trailingAnchor],[self.fovRow.topAnchor constraintEqualToAnchor:self.speedRow.bottomAnchor constant:1],[self.fovRow.bottomAnchor constraintLessThanOrEqualToAnchor:lb.bottomAnchor constant:-6],
[cam.leadingAnchor constraintEqualToAnchor:r.leadingAnchor constant:16],[cam.topAnchor constraintEqualToAnchor:r.topAnchor constant:11],[cam.widthAnchor constraintEqualToConstant:22],[cam.heightAnchor constraintEqualToConstant:22],[gt.leadingAnchor constraintEqualToAnchor:cam.trailingAnchor constant:9],[gt.centerYAnchor constraintEqualToAnchor:cam.centerYAnchor],[search.trailingAnchor constraintEqualToAnchor:r.trailingAnchor constant:-16],[search.centerYAnchor constraintEqualToAnchor:cam.centerYAnchor],[search.widthAnchor constraintEqualToConstant:22],[search.heightAnchor constraintEqualToConstant:22],[gd.leadingAnchor constraintEqualToAnchor:r.leadingAnchor constant:12],[gd.trailingAnchor constraintEqualToAnchor:r.trailingAnchor constant:-12],[gd.topAnchor constraintEqualToAnchor:cam.bottomAnchor constant:8],[gd.heightAnchor constraintEqualToConstant:1],[pt.leadingAnchor constraintEqualToAnchor:r.leadingAnchor constant:16],[pt.topAnchor constraintEqualToAnchor:gd.bottomAnchor constant:7],[ps.leadingAnchor constraintEqualToAnchor:pt.leadingAnchor],[ps.topAnchor constraintEqualToAnchor:pt.bottomAnchor constant:1],[self.grid.leadingAnchor constraintEqualToAnchor:r.leadingAnchor constant:14],[self.grid.trailingAnchor constraintEqualToAnchor:r.trailingAnchor constant:-14],[self.grid.topAnchor constraintEqualToAnchor:ps.bottomAnchor constant:8],[self.grid.bottomAnchor constraintEqualToAnchor:r.bottomAnchor constant:-10],
[tabs.leadingAnchor constraintEqualToAnchor:self.panelInner.leadingAnchor constant:54],[tabs.trailingAnchor constraintEqualToAnchor:self.panelInner.trailingAnchor constant:-54],[tabs.bottomAnchor constraintEqualToAnchor:self.panelInner.bottomAnchor constant:-10],[tabs.heightAnchor constraintEqualToConstant:46]]];
}
@end
