#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

FOUNDATION_EXPORT BOOL ZNSatellaStart(void);
FOUNDATION_EXPORT BOOL ZNSatellaIsLoaded(void);
FOUNDATION_EXPORT BOOL ZNSatellaIsStarted(void);

NS_ASSUME_NONNULL_END
