#import "ZNUIComponents.h"
#import <QuartzCore/QuartzCore.h>
UIColor *ZNColor(CGFloat r,CGFloat g,CGFloat b,CGFloat a){return [UIColor colorWithRed:r green:g blue:b alpha:a];}
UILabel *ZNLabel(NSString*t,CGFloat s,UIFontWeight w,UIColor*c){UILabel*l=[UILabel new];l.translatesAutoresizingMaskIntoConstraints=NO;l.text=t;l.font=[UIFont systemFontOfSize:s weight:w];l.textColor=c;return l;}
UIImage *ZNSymbol(NSString*n,CGFloat s){UIImage*i=[UIImage systemImageNamed:n];if(!i)return nil;return [i imageWithConfiguration:[UIImageSymbolConfiguration configurationWithPointSize:s weight:UIImageSymbolWeightSemibold]];}
@interface ZNGlowPanel()@property CAGradientLayer*fill;@end
@implementation ZNGlowPanel
-(instancetype)initWithFrame:(CGRect)f{if((self=[super initWithFrame:f])){self.layer.cornerRadius=16;self.layer.borderWidth=1;self.layer.borderColor=ZNColor(.08,.82,1,.58).CGColor;self.layer.shadowColor=ZNColor(0,.82,1,1).CGColor;self.layer.shadowOpacity=.25;self.layer.shadowRadius=10;self.layer.shadowOffset=CGSizeZero;_fill=[CAGradientLayer layer];_fill.colors=@[(id)ZNColor(.015,.08,.16,.94).CGColor,(id)ZNColor(.025,.035,.12,.92).CGColor,(id)ZNColor(.12,.015,.18,.88).CGColor];_fill.startPoint=CGPointMake(0,0);_fill.endPoint=CGPointMake(1,1);_fill.cornerRadius=16;[self.layer insertSublayer:_fill atIndex:0];}return self;}
-(void)layoutSubviews{[super layoutSubviews];self.fill.frame=self.bounds;}
@end
@interface ZNNeonSwitch()@property UIView*track;@property UIView*thumb;@end
@implementation ZNNeonSwitch
-(instancetype)initWithFrame:(CGRect)f{if((self=[super initWithFrame:f])){self.translatesAutoresizingMaskIntoConstraints=NO;[NSLayoutConstraint activateConstraints:@[[self.widthAnchor constraintEqualToConstant:58],[self.heightAnchor constraintEqualToConstant:31]]];_track=[UIView new];_track.userInteractionEnabled=NO;_track.layer.cornerRadius=15.5;_track.layer.borderWidth=1;[self addSubview:_track];_thumb=[UIView new];_thumb.userInteractionEnabled=NO;_thumb.backgroundColor=UIColor.whiteColor;_thumb.layer.cornerRadius=12;_thumb.layer.shadowColor=UIColor.whiteColor.CGColor;_thumb.layer.shadowOpacity=.55;_thumb.layer.shadowRadius=5;[self addSubview:_thumb];[self addTarget:self action:@selector(tap) forControlEvents:UIControlEventTouchUpInside];[self setOn:NO animated:NO];}return self;}
-(void)layoutSubviews{[super layoutSubviews];self.track.frame=self.bounds;self.thumb.frame=CGRectMake(self.on?CGRectGetWidth(self.bounds)-27:3,3.5,24,24);}
-(void)tap{[self setOn:!self.on animated:YES];[self sendActionsForControlEvents:UIControlEventValueChanged];}
-(void)setOn:(BOOL)v{[self setOn:v animated:NO];}
-(void)setOn:(BOOL)v animated:(BOOL)a{_on=v;void(^c)(void)=^{self.track.backgroundColor=v?ZNColor(0,.84,.94,.9):ZNColor(.20,.25,.38,.72);self.track.layer.borderColor=(v?ZNColor(.15,.96,1,.95):ZNColor(.42,.52,.70,.45)).CGColor;self.track.layer.shadowColor=(v?ZNColor(0,.92,1,1):UIColor.clearColor).CGColor;self.track.layer.shadowOpacity=v?.85:0;self.track.layer.shadowRadius=v?9:0;self.thumb.frame=CGRectMake(v?CGRectGetWidth(self.bounds)-27:3,3.5,24,24);};if(a)[UIView animateWithDuration:.18 animations:c];else c();}
@end
@interface ZNControlRow()@property UIImageView*icon;@property UILabel*label;@property(nonatomic,strong,readwrite)ZNNeonSwitch*neonSwitch;@end
@implementation ZNControlRow
-(instancetype)initWithTitle:(NSString*)t symbol:(NSString*)sym on:(BOOL)on{if((self=[super initWithFrame:CGRectZero])){self.translatesAutoresizingMaskIntoConstraints=NO;self.backgroundColor=ZNColor(.04,.08,.16,.7);self.layer.cornerRadius=12;self.layer.borderWidth=1;self.layer.borderColor=ZNColor(.18,.50,.78,.38).CGColor;_icon=[[UIImageView alloc]initWithImage:ZNSymbol(sym,18)];_icon.translatesAutoresizingMaskIntoConstraints=NO;_icon.tintColor=ZNColor(.28,.78,1,1);_label=ZNLabel(t,13,UIFontWeightSemibold,UIColor.whiteColor);_label.adjustsFontSizeToFitWidth=YES;_label.minimumScaleFactor=.72;_neonSwitch=[ZNNeonSwitch new];[_neonSwitch setOn:on animated:NO];[self addSubview:_icon];[self addSubview:_label];[self addSubview:_neonSwitch];[NSLayoutConstraint activateConstraints:@[[self.heightAnchor constraintEqualToConstant:55],[_icon.leadingAnchor constraintEqualToAnchor:self.leadingAnchor constant:13],[_icon.centerYAnchor constraintEqualToAnchor:self.centerYAnchor],[_icon.widthAnchor constraintEqualToConstant:24],[_icon.heightAnchor constraintEqualToConstant:24],[_label.leadingAnchor constraintEqualToAnchor:_icon.trailingAnchor constant:12],[_label.centerYAnchor constraintEqualToAnchor:self.centerYAnchor],[_neonSwitch.trailingAnchor constraintEqualToAnchor:self.trailingAnchor constant:-12],[_neonSwitch.centerYAnchor constraintEqualToAnchor:self.centerYAnchor],[_label.trailingAnchor constraintLessThanOrEqualToAnchor:_neonSwitch.leadingAnchor constant:-10]]];}return self;}
@end
@interface ZNSliderRow()@property UIImageView*icon;@property UILabel*label;@property(nonatomic,strong,readwrite)UILabel*valueLabel;@property(nonatomic,strong,readwrite)UISlider*slider;@end
@implementation ZNSliderRow
-(instancetype)initWithTitle:(NSString*)t symbol:(NSString*)sym value:(float)v valueText:(NSString*)vt tint:(UIColor*)tint{if((self=[super initWithFrame:CGRectZero])){self.translatesAutoresizingMaskIntoConstraints=NO;_icon=[[UIImageView alloc]initWithImage:ZNSymbol(sym,17)];_icon.translatesAutoresizingMaskIntoConstraints=NO;_icon.tintColor=ZNColor(.16,.83,1,1);_label=ZNLabel(t,12.4,UIFontWeightSemibold,UIColor.whiteColor);_valueLabel=ZNLabel(vt,11.5,UIFontWeightMedium,ZNColor(.88,.93,1,1));_valueLabel.textAlignment=NSTextAlignmentRight;_slider=[UISlider new];_slider.translatesAutoresizingMaskIntoConstraints=NO;_slider.minimumValue=0;_slider.maximumValue=1;_slider.value=v;_slider.minimumTrackTintColor=tint;_slider.maximumTrackTintColor=ZNColor(.28,.36,.52,.62);_slider.thumbTintColor=UIColor.whiteColor;[self addSubview:_icon];[self addSubview:_label];[self addSubview:_valueLabel];[self addSubview:_slider];[NSLayoutConstraint activateConstraints:@[[self.heightAnchor constraintEqualToConstant:62],[_icon.leadingAnchor constraintEqualToAnchor:self.leadingAnchor],[_icon.topAnchor constraintEqualToAnchor:self.topAnchor constant:2],[_icon.widthAnchor constraintEqualToConstant:23],[_icon.heightAnchor constraintEqualToConstant:23],[_label.leadingAnchor constraintEqualToAnchor:_icon.trailingAnchor constant:10],[_label.centerYAnchor constraintEqualToAnchor:_icon.centerYAnchor],[_valueLabel.trailingAnchor constraintEqualToAnchor:self.trailingAnchor],[_valueLabel.centerYAnchor constraintEqualToAnchor:_icon.centerYAnchor],[_slider.leadingAnchor constraintEqualToAnchor:_label.leadingAnchor],[_slider.trailingAnchor constraintEqualToAnchor:self.trailingAnchor],[_slider.topAnchor constraintEqualToAnchor:_icon.bottomAnchor constant:4],[_slider.bottomAnchor constraintEqualToAnchor:self.bottomAnchor constant:-2]]];}return self;}
@end
@interface ZNPresetCell()@property(nonatomic,strong,readwrite)UIImageView*imageView;@property(nonatomic,strong,readwrite)UILabel*caption;@end
@implementation ZNPresetCell
-(instancetype)initWithFrame:(CGRect)f{if((self=[super initWithFrame:f])){self.contentView.layer.cornerRadius=10;self.contentView.layer.masksToBounds=YES;self.contentView.layer.borderWidth=1;self.contentView.layer.borderColor=ZNColor(.24,.74,1,.72).CGColor;_imageView=[UIImageView new];_imageView.translatesAutoresizingMaskIntoConstraints=NO;_imageView.contentMode=UIViewContentModeScaleAspectFill;_imageView.clipsToBounds=YES;[self.contentView addSubview:_imageView];UIView*shade=[UIView new];shade.translatesAutoresizingMaskIntoConstraints=NO;shade.backgroundColor=ZNColor(.01,.015,.035,.72);[self.contentView addSubview:shade];_caption=ZNLabel(@"",9.2,UIFontWeightSemibold,UIColor.whiteColor);_caption.adjustsFontSizeToFitWidth=YES;_caption.minimumScaleFactor=.72;[shade addSubview:_caption];[NSLayoutConstraint activateConstraints:@[[_imageView.leadingAnchor constraintEqualToAnchor:self.contentView.leadingAnchor],[_imageView.trailingAnchor constraintEqualToAnchor:self.contentView.trailingAnchor],[_imageView.topAnchor constraintEqualToAnchor:self.contentView.topAnchor],[_imageView.bottomAnchor constraintEqualToAnchor:self.contentView.bottomAnchor],[shade.leadingAnchor constraintEqualToAnchor:self.contentView.leadingAnchor],[shade.trailingAnchor constraintEqualToAnchor:self.contentView.trailingAnchor],[shade.bottomAnchor constraintEqualToAnchor:self.contentView.bottomAnchor],[shade.heightAnchor constraintEqualToConstant:25],[_caption.leadingAnchor constraintEqualToAnchor:shade.leadingAnchor constant:6],[_caption.trailingAnchor constraintEqualToAnchor:shade.trailingAnchor constant:-4],[_caption.centerYAnchor constraintEqualToAnchor:shade.centerYAnchor]]];}return self;}
@end
